/**
 * generated by Xtext 2.18.0
 */
package org.jucmnav.turn.turn;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Regular End</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.jucmnav.turn.turn.TurnPackage#getRegularEnd()
 * @model
 * @generated
 */
public interface RegularEnd extends ReferencedBoundElement
{
} // RegularEnd
