/**
 * generated by Xtext 2.18.0
 */
package org.jucmnav.turn.turn;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Scenario Group</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.jucmnav.turn.turn.ScenarioGroup#getName <em>Name</em>}</li>
 *   <li>{@link org.jucmnav.turn.turn.ScenarioGroup#getLongName <em>Long Name</em>}</li>
 *   <li>{@link org.jucmnav.turn.turn.ScenarioGroup#getScenarios <em>Scenarios</em>}</li>
 * </ul>
 *
 * @see org.jucmnav.turn.turn.TurnPackage#getScenarioGroup()
 * @model
 * @generated
 */
public interface ScenarioGroup extends URNmodelElement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.jucmnav.turn.turn.TurnPackage#getScenarioGroup_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.jucmnav.turn.turn.ScenarioGroup#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Long Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Long Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Long Name</em>' containment reference.
   * @see #setLongName(LongName)
   * @see org.jucmnav.turn.turn.TurnPackage#getScenarioGroup_LongName()
   * @model containment="true"
   * @generated
   */
  LongName getLongName();

  /**
   * Sets the value of the '{@link org.jucmnav.turn.turn.ScenarioGroup#getLongName <em>Long Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Long Name</em>' containment reference.
   * @see #getLongName()
   * @generated
   */
  void setLongName(LongName value);

  /**
   * Returns the value of the '<em><b>Scenarios</b></em>' reference list.
   * The list contents are of type {@link org.jucmnav.turn.turn.ScenarioDef}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Scenarios</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scenarios</em>' reference list.
   * @see org.jucmnav.turn.turn.TurnPackage#getScenarioGroup_Scenarios()
   * @model
   * @generated
   */
  EList<ScenarioDef> getScenarios();

} // ScenarioGroup
