/**
 * generated by Xtext 2.18.0
 */
package org.jucmnav.turn.turn;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>UR Nmodel Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.jucmnav.turn.turn.TurnPackage#getURNmodelElement()
 * @model
 * @generated
 */
public interface URNmodelElement extends EObject
{
} // URNmodelElement
