/**
 * generated by Xtext 2.12.0
 */
package org.xtext.project.turn.tcolab.ide;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class TURNIdeSetup /* implements TURNStandaloneSetup  */{
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nTURNRuntimeModule cannot be resolved.");
  }
}
