/**
 * generated by Xtext 2.18.0
 */
package org.jucmnav.turn.turn.impl;

import org.eclipse.emf.ecore.EClass;

import org.jucmnav.turn.turn.PathBodyNode;
import org.jucmnav.turn.turn.TurnPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Path Body Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PathBodyNodeImpl extends ReferencedBoundElementImpl implements PathBodyNode
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PathBodyNodeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TurnPackage.Literals.PATH_BODY_NODE;
  }

} //PathBodyNodeImpl
