/**
 * generated by Xtext 2.18.0
 */
package org.jucmnav.turn.turn.impl;

import org.eclipse.emf.ecore.EClass;

import org.jucmnav.turn.turn.RegularEnd;
import org.jucmnav.turn.turn.TurnPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Regular End</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RegularEndImpl extends ReferencedBoundElementImpl implements RegularEnd
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RegularEndImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TurnPackage.Literals.REGULAR_END;
  }

} //RegularEndImpl
