/*
 * generated by Xtext 2.12.0
 */
package org.xtext.project.turn.tcolab.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2

import org.xtext.project.turn.TurnStandaloneSetup
import mcgill.xtext.turn.TURNRuntimeModule

/**
 * Initialization support for running Xtext languages as language servers.
 */
class TURNIdeSetup extends TURNStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new TURNRuntimeModule, new TURNIdeModule))
	}
	
}
