/*
 * generated by Xtext 2.18.0
 */
package org.jucmnav.turn.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTurnScopeProvider extends DelegatingScopeProvider {
}
