/**
 * generated by Xtext 2.18.0
 */
package org.jucmnav.turn;

import org.jucmnav.turn.AbstractTurnRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class TurnRuntimeModule extends AbstractTurnRuntimeModule {
}
