/**
 * generated by Xtext 2.18.0
 */
package org.jucmnav.turn;

import org.jucmnav.turn.TurnStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class TurnStandaloneSetup extends TurnStandaloneSetupGenerated {
  public static void doSetup() {
    new TurnStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
