/*
 * generated by Xtext 2.12.0
 */
package mcgill.xtext.turn.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2

import mcgill.xtext.turn.TURNStandaloneSetup
import mcgill.xtext.turn.TURNRuntimeModule

/**
 * Initialization support for running Xtext languages as language servers.
 */
class TURNIdeSetup extends TURNStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new TURNRuntimeModule, new TURNIdeModule))
	}
	
}
