/**
 * generated by Xtext 2.18.0
 */
package org.jucmnav.turn.scoping;

import org.jucmnav.turn.scoping.AbstractTurnScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class TurnScopeProvider extends AbstractTurnScopeProvider {
}
