/**
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl.TURNRuntimeModule;
import org.xtext.example.mydsl.TURNStandaloneSetup;
import org.xtext.example.mydsl.ide.TURNIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class TURNIdeSetup extends TURNStandaloneSetup {
  @Override
  public Injector createInjector() {
    TURNRuntimeModule _tURNRuntimeModule = new TURNRuntimeModule();
    TURNIdeModule _tURNIdeModule = new TURNIdeModule();
    return Guice.createInjector(Modules2.mixin(_tURNRuntimeModule, _tURNIdeModule));
  }
}
