/**
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.mydsl.ide;

import org.xtext.example.mydsl.ide.AbstractTURNIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class TURNIdeModule extends AbstractTURNIdeModule {
}
