/**
 * generated by Xtext 2.18.0
 */
package org.jucmnav.turn.validation;

import org.jucmnav.turn.validation.AbstractTurnValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class TurnValidator extends AbstractTurnValidator {
}
